# Generated by Django 4.2.13 on 2024-05-24 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("vendors", "0003_vendorperformancehistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="vendor",
            old_name="on_time_delivery_code",
            new_name="on_time_delivery_rate",
        ),
    ]
